-- BowlPoint Full Competition TEST population
-- 1) Create the competition in BowlPoint.
-- 2) Replace PUT-YOUR-COMPETITION-UUID-HERE.
-- 3) Run this script in Supabase SQL Editor.
-- Intended for a FOURS competition and 32-team draw testing.

BEGIN;

DO $$
DECLARE
  v_competition_id uuid := 'PUT-YOUR-COMPETITION-UUID-HERE';
  v_club record;
  v_players uuid[];
  v_team_id uuid;
  v_team_no integer;
  v_team_in_club integer;
BEGIN
  IF v_competition_id = 'PUT-YOUR-COMPETITION-UUID-HERE'::uuid THEN
    RAISE EXCEPTION 'Set v_competition_id before running the script.';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.competitions WHERE id=v_competition_id) THEN
    RAISE EXCEPTION 'Competition % does not exist.', v_competition_id;
  END IF;

  IF EXISTS (SELECT 1 FROM public.competitions WHERE id=v_competition_id AND format <> 'fours') THEN
    RAISE EXCEPTION 'Competition % is not configured as Fours.', v_competition_id;
  END IF;

  -- Reusable TEST clubs.
  INSERT INTO public.clubs(name, short_name, active)
  SELECT 'TEST - Club '||lpad(n::text,2,'0'),
         'TST'||lpad(n::text,2,'0'), true
  FROM generate_series(1,8) g(n)
  WHERE NOT EXISTS (
    SELECT 1 FROM public.clubs c
    WHERE c.name='TEST - Club '||lpad(n::text,2,'0')
  );

  -- 16 players per club = 128 players.
  -- display_name is generated by the current schema, so do not insert it.
  INSERT INTO public.players(first_name,last_name,club_id,active)
  SELECT 'Test'||lpad(((club_no-1)*16+player_no)::text,3,'0'),
         'Player', c.id, true
  FROM generate_series(1,8) clubs(club_no)
  CROSS JOIN generate_series(1,16) players(player_no)
  JOIN public.clubs c
    ON c.name='TEST - Club '||lpad(club_no::text,2,'0')
  WHERE NOT EXISTS (
    SELECT 1 FROM public.players p
    WHERE p.first_name='Test'||lpad(((club_no-1)*16+player_no)::text,3,'0')
      AND p.last_name='Player' AND p.club_id=c.id
  );

  -- Register TEST clubs.
  INSERT INTO public.competition_clubs(competition_id,club_id)
  SELECT v_competition_id,c.id
  FROM public.clubs c
  WHERE c.name LIKE 'TEST - Club %'
  ORDER BY c.name LIMIT 8
  ON CONFLICT DO NOTHING;

  IF EXISTS (
    SELECT 1 FROM public.competition_teams
    WHERE competition_id=v_competition_id
      AND team_name LIKE 'TEST - Team %'
  ) THEN
    RAISE EXCEPTION 'This competition already contains TEST teams.';
  END IF;

  -- 8 clubs x 4 teams = 32 teams; 4 unique players per team.
  FOR v_club IN
    SELECT c.id,c.name,row_number() OVER(ORDER BY c.name)::integer AS club_no
    FROM public.clubs c
    WHERE c.name LIKE 'TEST - Club %'
    ORDER BY c.name LIMIT 8
  LOOP
    SELECT array_agg(p.id ORDER BY p.id)
    INTO v_players
    FROM (
      SELECT p.id
      FROM public.players p
      WHERE p.club_id=v_club.id
        AND p.first_name LIKE 'Test%' AND p.last_name='Player'
      ORDER BY p.id LIMIT 16
    ) p;

    IF coalesce(array_length(v_players,1),0) <> 16 THEN
      RAISE EXCEPTION 'Club % does not have 16 TEST players.',v_club.name;
    END IF;

    FOR v_team_in_club IN 1..4 LOOP
      v_team_no=((v_club.club_no-1)*4)+v_team_in_club;

      INSERT INTO public.competition_teams
        (competition_id,club_id,team_number,team_name,status)
      VALUES
        (v_competition_id,v_club.id,v_team_no,
         'TEST - Team '||lpad(v_team_no::text,2,'0'),'active')
      RETURNING id INTO v_team_id;

      INSERT INTO public.competition_team_players
        (competition_team_id,player_id,position,position_order)
      VALUES
        (v_team_id,v_players[(v_team_in_club-1)*4+1],'lead',1),
        (v_team_id,v_players[(v_team_in_club-1)*4+2],'second',2),
        (v_team_id,v_players[(v_team_in_club-1)*4+3],'third',3),
        (v_team_id,v_players[(v_team_in_club-1)*4+4],'skip',4);
    END LOOP;
  END LOOP;

  RAISE NOTICE '32 TEST teams / 128 TEST players created.';
END $$;

COMMIT;

-- Verification
SELECT ct.team_number,ct.team_name,c.short_name,COUNT(ctp.player_id) AS players
FROM public.competition_teams ct
JOIN public.clubs c ON c.id=ct.club_id
LEFT JOIN public.competition_team_players ctp ON ctp.competition_team_id=ct.id
WHERE ct.competition_id='PUT-YOUR-COMPETITION-UUID-HERE'::uuid
  AND ct.team_name LIKE 'TEST - Team %'
GROUP BY ct.id,ct.team_number,ct.team_name,c.short_name
ORDER BY ct.team_number;
